import Button from "@/components/Button";
import Form from "@/components/Form";
import Layout from "@/components/Layout";
import Table from "@/components/Table";
import Client from "@/core/Client";
import Head from "next/head";
import { useState } from "react";

export default function Home() {
	
	
	const [client, setCliente] = useState(Client.emptyClient())
	const [formState, setFormState] = useState<'table' | 'form'>('table')
	
	const mockClients = [
		new Client("Arthur", 21, "1"),
		new Client("Victor", 22, "2"),
		new Client("Gabi", 23, "3"),
		new Client("Joao", 24, "4"),
	];


	function selectedClient(client: Client) {
		setCliente(client)
		setFormState('form')
	}
	function deletedClient(client: Client) {
		console.log(client.name, "excluido");
	}

    function saveClient(client: Client){
        console.log(client)
		setFormState('table')
    }
    function newClient(client: Client){
        setCliente(Client.emptyClient())
		setFormState('form')
    }

	return (
		<>
			<Head>
				<title>Home</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div
				className={`
					flex h-screen items-center justify-center
					bg-gradient-to-r from-blue-500 to-indigo-700
					text-white
				`}
			>
				<Layout title="Simple Register">
					{formState === 'table' ? (
						<>
						<div className={`flex justify-center `}>
							<Button
								onClick={newClient}
								className={`
									bg-gradient-to-r from-indigo-500 to-indigo-700
									mb-4
								`}
							>
								New Client
							</Button>
						</div>

						<Table
							clients={mockClients}
							selectedClient={selectedClient}
							deletedClient={deletedClient}
						/>
					</>
					) : (
						<Form 
							client={client}
							clientChanged={saveClient}
							cancel={()=> setFormState('table')}
						/>
					)}
					
				</Layout>
			</div>
		</>
	);
}
